chat/urls.py
from django.urls import path

from . import views

app_name = "chat"

urlpatterns = [
    path('<int:room>/', views.room, name="room"),
    path('token', views.ChatTokenGeneratorApiView.as_view()),
    path('messages/<int:conversion>', views.MessageListAPIView.as_view()),
    path('contacts/',views.ChatNewContactApiView.as_view()),
    path('', views.ChatListCreateApiView.as_view())
]

dchat/urls.py
from django.contrib import admin
from django.contrib.auth import get_user_model
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include("chat.urls")),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.authtoken')),
    path('wazo/', TemplateView.as_view(template_name="wazo.html",)),
path('', TemplateView.as_view(template_name="index.html", extra_context={'users': get_user_model().objects.all()})),
]

chat/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.conf import settings
from datetime import datetime,timedelta
from django.utils import timezone
from django.utils.crypto import get_random_string
import binascii
import os

# Create your models here.
class ConversionManager(models.Manager):
    def get_room(self, user1, user2):
        print(user1.pk, user2.pk)
        conversion = self.get_queryset().filter(
            is_group=False,
            participants=user1
        ).filter(participants=user2)
        if conversion.exists():
            return conversion.first()
        else:
            conversion = Conversion.objects.create(name=get_random_string(length=12), is_group=False)
            conversion.participants.add(user1, user2)
            return conversion

    def room_exists(self,user1,user2):
        conversion = self.get_queryset().filter(
            is_group=False,
            participants=user1
        ).filter(participants=user2)
        return conversion.exists()


class WebsocketToken(models.Model):
    key = models.CharField(max_length=255,unique=True)
    user=models.ForeignKey(get_user_model(),on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)
    expired = models.DateTimeField()

    def save(self, *args, **kwargs):
        if not self.key:
            self.key = self.generate_key()
        self.expired=datetime.now()+timedelta(minutes=30)
        return super().save(*args, **kwargs)

    def generate_key(self):
        return binascii.hexlify(os.urandom(50)).decode()

    def is_expired(self):
        return self.expired >timezone.now()

    def __str__(self):
        return self.key

class Conversion(models.Model):
    objects = ConversionManager()
    name = models.CharField(max_length=255)
    participants = models.ManyToManyField(get_user_model())
    is_group = models.BooleanField(default=False)


class Message(models.Model):
    conversion = models.ForeignKey('chat.Conversion', on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class UserStatusEnum(models.TextChoices):
    ONLINE='online',
    OFFLINE='offline'

class User(AbstractUser):
    status=models.CharField(choices=UserStatusEnum.choices,max_length=50,default=UserStatusEnum.OFFLINE)

chat/views.py
from django.shortcuts import render
from rest_framework.generics import CreateAPIView, ListCreateAPIView, ListAPIView
from rest_framework.permissions import IsAuthenticated

from .models import WebsocketToken, Conversion, Message, get_user_model
from django.contrib.auth.models import User
from .serializers import WebSocketTokenSerializer, ConversionSerializer, MessageSerializer, UserSerializer


# Create your views here.


class ChatTokenGeneratorApiView(CreateAPIView):
    serializer_class = WebSocketTokenSerializer
    permission_classes = (IsAuthenticated,)

    def get_queryset(self):
        return WebsocketToken.objects.all()


class ChatListCreateApiView(ListCreateAPIView):
    serializer_class = ConversionSerializer

    def get_queryset(self):
        return Conversion.objects.filter(participants=self.request.user)


class ChatNewContactApiView(ListAPIView):
    serializer_class = UserSerializer

    def get_queryset(self):
        return get_user_model().objects.exclude(conversion__participants=self.request.user)


class MessageListAPIView(ListAPIView):
    serializer_class = MessageSerializer

    def get_queryset(self):
        return Message.objects.filter(conversion_id=self.kwargs.get('conversion'))


def room(request, room):
    return render(request, 'room.html', {'room': room})

user/views.py
from django.shortcuts import render

# Create your views here.

chat/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<ul>
    {% for uuser in users %}
        {% if user.pk == uuser.pk %}
            <li><a href="#">{{ uuser.username }} </a> (You)</li>
        {% else %}
            <li><a href="{% url 'chat:room' room=uuser.pk %}">{{ uuser.username }} </a></li>
        {% endif %}

    {% endfor %}


</ul>
<script>

</script>
</body>
</html>

chat/templates/room.html
<!-- chat/templates/chat/room.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>
<textarea id="chat-log" cols="100" rows="20"></textarea><br>
<input id="chat-message-input" type="text" size="100"><br>
<input id="chat-message-submit" type="button" value="Send">
{{ room|json_script:"room" }}
<script>
    const roomName = JSON.parse(document.getElementById('room').textContent);

    const chatSocket = new WebSocket(
        'ws://'
        + window.location.host
        + '/ws/chat/'
        + roomName
        + '/?key=45207a56fb947cbeb9ad0133ad1d6833c50a30fbc5cdcea9a949cf862c6547740e34677e28316c4e0a21fece6cc6d2c68e49'
    );


    chatSocket.onmessage = function (e) {
        console.log(e.data)
        const data = JSON.parse(e.data);
        document.querySelector('#chat-log').value += (data.message + '\n');
    };

    chatSocket.onclose = function (e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function (e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function (e) {
        const messageInputDom = document.querySelector('#chat-message-input');
        const message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'message': message
        }));
        messageInputDom.value = '';
    };

    const notifySocket = new WebSocket(
        'ws://'
        + window.location.host
        + '/ws/chat/'
        + 'notify'
        + '?key=a868fed54f8f20f1d97988cbc0fac2a952299cb052d6e4607113f4054697af3cf9289e62ceac664b51ae76e57a716afbb895'
        ,
    );
    notifySocket.onopen = function (e) {
        console.log(e)
    }
    notifySocket.onmessage = function (e) {
        console.log(e)
    }
</script>
</body>
</html>

chat/templates/wazo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<button onclick="call()">Make Call</button>
<script src="https://unpkg.com/@wazo/sdk@0.33.28/dist/wazo-sdk.js"></script>
<script>
    Wazo.Auth.setHost("wazo.tylextech.com");

    async function login(){
         let session=await Wazo.Auth.logIn("kei@kei.com","kei123")
        console.log(session)
    }

    login()
    async function call(){
        let room= await Wazo.Room.connect({extension:12345,audio:true,video:true})
        console.log(room)
        room.turnCameraOn();
    }
</script>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<ul>
    {% for user in users %}
         <li>{{ user.username }}</li>
    {% endfor %}


</ul>
</body>
</html>